services:
  database:
    image: postgres:18-bookworm
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB:-zordbase} -U ${POSTGRES_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-zordbase}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
    volumes:
      - db_data:/var/lib/postgresql

  migrater:
    image: zordbase-backend
    build:
      context: ./back
      dockerfile: Dockerfile.dev
    command: ["sh", "-c", "npx drizzle-kit migrate"]
    depends_on:
      database:
        condition: service_healthy
    container_name: migrater
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-secret}@database:5432/${POSTGRES_DB:-zordbase}
    volumes:
      - ./back/src:/app/src
      - ./back/drizzle:/app/drizzle

  back:
    image: zordbase-backend
    build:
      context: ./back
      dockerfile: Dockerfile.dev
    container_name: backend
    depends_on:
      database:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-secret}@database:5432/${POSTGRES_DB:-zordbase}
    volumes:
      - ./back/src:/app/src
      - ./words:/words
    ports:
      - 3000:3000

  front:
    image: zordbase-frontend
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    container_name: frontend
    command: npm run dev -- --host 0.0.0.0
    environment:
      - DEV_API=http://backend:3000
    volumes:
      - ./front/src:/app/src
    ports:
      - 6540:6540

volumes:
  db_data: